services:
  mongo:
    image: mongo:7-jammy
    
    container_name: mongodb
    
    ports:
      - "27007:27017"
    
    volumes:
      - ./mongodb:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME= ${ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD= ${ROOT_PASSWORD}
    
    networks:
      - backend

    restart: always


networks:
  backend: 